apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: atym-selfsigned-ca
  namespace: cert-manager
spec:
  dnsNames:
  - localhost
  isCA: true
  secretName: root-secret
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  subject: # needed later for local trust store
    organizations:
      - atym.io
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: atym-ca-issuer
spec:
  ca:
    secretName: root-secret
